declare -A FILE_MAP

FILE_MAP["./testPictureFolder/"]="*.png *.jpg *.jpeg *.gif"
FILE_MAP["./testDocumentFolder/"]="*.txt *.pdf"
FILE_MAP["./testTrashFolder/"]="*.trash"
FILE_MAP["./testVideoFolder/"]="*.mp4 *.mov"
