declare -A FILE_MAP

home="$HOME/Documents/dele/cyber-cleand/bash/"

FILE_MAP["$home/testPictureFolder/"]="*.png *.jpg *.jpeg *.gif"
FILE_MAP["$home/testDocumentFolder/"]="*.txt *.pdf"
FILE_MAP["$home/testTrashFolder/"]="*.trash"
FILE_MAP["$home/testVideoFolder/"]="*.mp4 *.mov"
