declare -A FILE_MAP

# Directories that would be scanned and check for changes 

WATCH_DIRS=(
  "$HOME/Documents/dele/cyber-cleand/bash"
  "$HOME/Documents/dele/cyber-cleand/rust"
)

home="$HOME/Documents/dele/cyber-cleand/bash/"

# the test folders are for debugging 
# u can add ur main folders in home directory there 
# and changing home to be HOME not the route i set

FILE_MAP["$home/testPictureFolder/"]="*.png *.jpg *.jpeg *.gif"
FILE_MAP["$home/testDocumentFolder/"]="*.txt *.pdf"
FILE_MAP["$home/testTrashFolder/"]="*.trash"
FILE_MAP["$home/testVideoFolder/"]="*.mp4 *.mov"


